"""
Saathi Web Sandbox — Text-to-Speech Module.
Converts Hindi text to audio using OpenAI TTS API.
Supports per-persona voice selection and streaming TTS for lower latency.
"""

import time
from typing import AsyncGenerator
from openai import AsyncOpenAI

from config import OPENAI_API_KEY, TTS_MODEL, TTS_VOICE, TTS_VOICES

_client = None


def _get_client() -> AsyncOpenAI:
    global _client
    if _client is None:
        _client = AsyncOpenAI(api_key=OPENAI_API_KEY)
    return _client


def get_voice_for_persona(persona: str | None) -> str:
    """Get the TTS voice for a given persona, falling back to default."""
    if persona and persona in TTS_VOICES:
        return TTS_VOICES[persona]
    return TTS_VOICE


async def synthesize(text: str, persona: str | None = None) -> tuple[bytes | None, float]:
    """
    Convert Hindi text to MP3 audio bytes (non-streaming, used as fallback).

    Args:
        text: Hindi text in Devanagari script.
        persona: Optional persona key to select the appropriate voice.

    Returns:
        (mp3_bytes, latency_seconds)
    """
    if not text or not text.strip():
        return None, 0.0

    voice = get_voice_for_persona(persona)
    start_time = time.time()

    try:
        response = await _get_client().audio.speech.create(
            model=TTS_MODEL,
            voice=voice,
            input=text,
            response_format="mp3",
            speed=1.0,
        )

        audio_bytes = response.content
        latency = time.time() - start_time

        print(f"  🔊 TTS ({voice}): \"{text[:30]}...\" ({latency:.2f}s, {len(audio_bytes)} bytes)")
        return audio_bytes, latency

    except Exception as e:
        latency = time.time() - start_time
        print(f"  ❌ TTS Error: {e}")
        return None, latency


async def synthesize_streaming(
    text: str,
    persona: str | None = None,
    chunk_size: int = 4096,
) -> AsyncGenerator[bytes, None]:
    """
    Stream TTS audio bytes as they're generated by OpenAI.
    Uses PCM format for lowest latency and direct Web Audio API playback.

    Args:
        text: Hindi text in Devanagari script.
        persona: Optional persona key to select the appropriate voice.
        chunk_size: Size of each yielded audio chunk in bytes.

    Yields:
        Raw PCM audio chunks (24kHz, 16-bit, mono).
    """
    if not text or not text.strip():
        return

    voice = get_voice_for_persona(persona)
    start_time = time.time()
    first_chunk = True

    try:
        async with _get_client().audio.speech.with_streaming_response.create(
            model=TTS_MODEL,
            voice=voice,
            input=text,
            response_format="pcm",  # Raw PCM: 24kHz, 16-bit, mono — lowest latency
            speed=1.0,
        ) as response:
            async for chunk in response.iter_bytes(chunk_size=chunk_size):
                if first_chunk:
                    latency = time.time() - start_time
                    print(f"  🔊 TTS stream first chunk ({voice}): \"{text[:30]}...\" ({latency:.2f}s)")
                    first_chunk = False
                yield chunk

    except Exception as e:
        print(f"  ❌ TTS Streaming Error: {e}")
        # Fall back to non-streaming synthesize — caller should handle this
        raise
